CREATE TABLE IF NOT EXISTS usuarios(
	id_usuario INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(30) NOT NULL,
	apellido VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE KEY,
	usuario VARCHAR(20) NOT NULL,
	pass VARCHAR(50) NOT NULL,
	id_perfil INTEGER(11) NOT NULL DEFAULT 2,
	baja VARCHAR(2) NOT NULL DEFAULT 'NO',
	PRIMARY KEY (id_usuario)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS perfiles(
	id_perfil INTEGER(10) NOT NULL DEFAULT 2,
	descripcion VARCHAR(50) NOT NULL,
	PRIMARY KEY (id_perfil)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

ALTER TABLE `usuarios` CHANGE `pass` `password` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `usuarios` CHANGE `usuario_id` `id_usuario` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;